vim.keymap.set("v", "(", "c(<ESC>pa)")
vim.keymap.set("v", "[", "c[<ESC>pa]")
vim.keymap.set("v", "{", "c{<ESC>pa}")
vim.keymap.set("v", "'", "c'<ESC>pa'")
vim.keymap.set("v", '"', 'c"<ESC>pa"')
vim.keymap.set("v", "`", "c`<ESC>pa`")
